# Generated by Django 4.2.4 on 2023-11-16 13:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=250, populate_from='name', unique=True),
        ),
    ]
